# Docker compose file for creating a Kudu cluster with 3 masters, 3 tablet
# servers and an Impala daemon.
version: "3"
services:
  kudu-master-0:
    image: ${KUDU_IMAGE}
    container_name: ${MASTER_CONTAINER}
    ports:
      - 7051:7051
      - 8051:8051
    command: ["master"]
    environment:
      - KUDU_MASTERS=${KUDU_MASTERS}
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
        --rpc_bind_addresses=0.0.0.0:7051
        --rpc_advertised_addresses=${DOCKER_IP}:7051
        --webserver_port=8051
        --webserver_advertised_addresses=${DOCKER_IP}:8051
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false

  kudu-master-1:
    image: ${KUDU_IMAGE}
    container_name: ${MASTER_CONTAINER}-1
    ports:
      - 7151:7151
      - 8151:8151
    command: ["master"]
    environment:
      - KUDU_MASTERS=${KUDU_MASTERS}
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
        --rpc_bind_addresses=0.0.0.0:7151
        --rpc_advertised_addresses=${DOCKER_IP}:7151
        --webserver_port=8151
        --webserver_advertised_addresses=${DOCKER_IP}:8151
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false

  kudu-master-2:
    image: ${KUDU_IMAGE}
    container_name: ${MASTER_CONTAINER}-2
    ports:
      - 7251:7251
      - 8251:8251
    command: ["master"]
    environment:
      - KUDU_MASTERS=${KUDU_MASTERS}
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
        --rpc_bind_addresses=0.0.0.0:7251
        --rpc_advertised_addresses=${DOCKER_IP}:7251
        --webserver_port=8251
        --webserver_advertised_addresses=${DOCKER_IP}:8251
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false

  kudu-tserver-0:
    image: ${KUDU_IMAGE}
    depends_on:
      - kudu-master-0
      - kudu-master-1
      - kudu-master-2
    ports:
      - 7050:7050
      - 8050:8050
    command: ["tserver"]
    environment:
      - KUDU_MASTERS=${KUDU_MASTERS}
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
        --rpc_bind_addresses=0.0.0.0:7050
        --rpc_advertised_addresses=${DOCKER_IP}:7050
        --webserver_port=8050
        --webserver_advertised_addresses=${DOCKER_IP}:8050
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false

  kudu-tserver-1:
    image: ${KUDU_IMAGE}
    depends_on:
      - kudu-master-0
      - kudu-master-1
      - kudu-master-2
    ports:
      - 7150:7150
      - 8150:8150
    command: ["tserver"]
    environment:
      - KUDU_MASTERS=${KUDU_MASTERS}
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
        --rpc_bind_addresses=0.0.0.0:7150
        --rpc_advertised_addresses=${DOCKER_IP}:7150
        --webserver_port=8150
        --webserver_advertised_addresses=${DOCKER_IP}:8150
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false

  kudu-tserver-2:
    image: ${KUDU_IMAGE}
    depends_on:
      - kudu-master-0
      - kudu-master-1
      - kudu-master-2
    ports:
      - 7250:7250
      - 8250:8250
    command: ["tserver"]
    environment:
      - KUDU_MASTERS=${KUDU_MASTERS}
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
        --rpc_bind_addresses=0.0.0.0:7250
        --rpc_advertised_addresses=${DOCKER_IP}:7250
        --webserver_port=8250
        --webserver_advertised_addresses=${DOCKER_IP}:8250
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false

  kudu-tserver-3:
    image: ${KUDU_IMAGE}
    depends_on:
      - kudu-master-0
      - kudu-master-1
      - kudu-master-2
    ports:
      - 7350:7350
      - 8350:8350
    command: ["tserver"]
    environment:
      - KUDU_MASTERS=${KUDU_MASTERS}
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
        --rpc_bind_addresses=0.0.0.0:7350
        --rpc_advertised_addresses=${DOCKER_IP}:7350
        --webserver_port=8350
        --webserver_advertised_addresses=${DOCKER_IP}:8350
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false

  impala-daemon-0:
    image: ${IMPALA_IMAGE}
    container_name: ${IMPALA_CONTAINER}
    depends_on:
      - kudu-tserver-0
      - kudu-tserver-1
      - kudu-tserver-2
    ports:
      - 21000:21000
      - 21050:21050
      - 25000:25000
      - 25010:25010
      - 25020:25020
    command: ["impala"]
    environment:
      - KUDU_MASTERS=${KUDU_MASTERS}
