# docker compose for a simple (one of each) kafka cluster
version: "2"
services:
    zookeeper:
        image: ${ZOOKEEPER_IMAGE}
        ports:
            - "2181:2181"
    kafka:
        image: ${KAFKA_HOST}
        ports:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_IP}
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
networks:
    default:
        external:
            name: ${DOCKER_NETWORK}
