# docker compose for a simple (one of each) kafka cluster
version: "2"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: ${KUDU_QUICKSTART_IP:?Please set KUDU_QUICKSTART_IP environment variable}
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
networks:
    default:
        external:
            name: docker_default
